const GalleryData =[
    {
    id:Math.random(),
    title:"Cherries",
    text:"",
    rate:"2",
    },
    {
        id:Math.random(),
        title:"Hazelnut",
        text:"",
        rate:"2",
    },
    {
        id:Math.random(),
        title:"Lotus",
        text:"",
        rate:"2",
       
    },
    {
        id:Math.random(),
        title:"Pistachio",
        text:"",
        rate:"2",
    },
    {
        id:Math.random(),
        title:"Strawberry",
        text:"",
        rate:"2",
    },
    {
        id:Math.random(),
        title:"lamon",
        text:"",
        rate:"2",
    },
    {
        id:Math.random(),
        title:"Blueberry",
        text:"",
        rate:"2",
    },
];
export default GalleryData;